spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: shop_user
    password: devpassword
  jpa:
    show-sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE