INSERT INTO products (slug, serial_number, name, maker, model_year, price_cents, grade, category, category_slug, blurb, panel_json, active) VALUES
                                                                                                                                                ('roland-juno-106','JN-441027','Juno-106','Roland',1984,189500,'A','Synthesizers','synthesizers','Six-voice analogue polysynth with the chorus that defined a decade of records.','{"hue":32,"keys":true,"faders":8,"knobs":3,"wood":true}',true),
                                                                                                                                                ('korg-ms-20','MS-118392','MS-20','Korg',1979,242000,'B','Synthesizers','synthesizers','Semi-modular monosynth with the most aggressive filter Korg ever shipped.','{"hue":8,"keys":true,"faders":4,"knobs":7,"wood":false}',true),
                                                                                                                                                ('roland-tr-808','TR-208814','TR-808','Roland',1982,675000,'A','Drum machines','drum-machines','The drum machine half of modern music stands on.','{"hue":20,"keys":false,"faders":11,"knobs":4,"wood":true}',true),
                                                                                                                                                ('yamaha-dx7','DX-903117','DX7','Yamaha',1983,84000,'B','Synthesizers','synthesizers','Six-operator FM that ended the analogue era for a while.','{"hue":200,"keys":true,"faders":2,"knobs":0,"wood":false}',true),
                                                                                                                                                ('moog-minimoog-d','MM-7741','Minimoog Model D','Moog',1974,680000,'B','Synthesizers','synthesizers','Three oscillators into the ladder filter -- the reference mono synth.','{"hue":24,"keys":true,"faders":0,"knobs":9,"wood":true}',true),
                                                                                                                                                ('roland-sh-101','SH-227845','SH-101','Roland',1983,145000,'B','Synthesizers','synthesizers','One oscillator, one filter, a sequencer, and no menu anywhere.','{"hue":210,"keys":true,"faders":9,"knobs":2,"wood":false}',true),
                                                                                                                                                ('korg-polysix','PS-33218','Polysix','Korg',1982,65000,'D','Synthesizers','synthesizers','Six-voice programmable poly, sold for restoration -- the classic battery fault got here first.','{"hue":30,"keys":true,"faders":1,"knobs":6,"wood":true}',true),
                                                                                                                                                ('oberheim-ob-xa','OB-81455','OB-Xa','Oberheim',1981,520000,'C','Synthesizers','synthesizers','Eight Curtis-filtered voices and the brass sound of 1981.','{"hue":220,"keys":true,"faders":0,"knobs":8,"wood":false}',true),
                                                                                                                                                ('sequential-prophet-5','PR-3-2288','Prophet-5 Rev 3','Sequential',1981,1150000,'A','Synthesizers','synthesizers','Rev 3 with Curtis chips, fully calibrated.','{"hue":30,"keys":true,"faders":5,"knobs":9,"wood":true}',true),
                                                                                                                                                ('roland-tr-909','TR-909-1177','TR-909','Roland',1984,790000,'B','Drum machines','drum-machines','Analogue drums with sampled hats -- the bridge machine techno never put down.','{"hue":45,"keys":false,"faders":10,"knobs":3,"wood":false}',true),
                                                                                                                                                ('linndrum-lm-2','LD-2231','LinnDrum LM-2','Linn',1982,360000,'B','Drum machines','drum-machines','Sampled drums in a steel box -- the backbone of early-80s radio.','{"hue":40,"keys":false,"faders":6,"knobs":2,"wood":false}',true),
                                                                                                                                                ('boss-ce-1','CE-70441','CE-1 Chorus Ensemble','Boss',1976,61500,'C','Effects','effects','The first chorus pedal, and the preamp people record through on purpose.','{"hue":210,"keys":false,"faders":0,"knobs":4,"wood":false}',true),
                                                                                                                                                ('roland-space-echo-201','RE-140882','RE-201 Space Echo','Roland',1974,158000,'B','Effects','effects','Tape echo with spring reverb -- the delay that moves.','{"hue":26,"keys":false,"faders":3,"knobs":5,"wood":true}',true),
                                                                                                                                                ('lexicon-224','LX-224-0912','224 Digital Reverb','Lexicon',1980,440000,'C','Effects','effects','Early digital reverb -- the hall on half the records of 1980.','{"hue":90,"keys":false,"faders":4,"knobs":2,"wood":false}',true);
-- One inventory row per product, all starting on the floor.
INSERT INTO inventory (product_id, location)
SELECT id, 'FLOOR' FROM products;